CREATE TABLE `founders` (
	`id` text PRIMARY KEY,
	`name` text,
	`email` text,
	`whatsapp` text,
	`linkedin` text,
	`your_photo` text,
	`status` text,
	`confirm_enrolment` text,
	`left_program` text,
	`existing_project_idea` text,
	`project_explanation` text,
	`existing_cofounder_name` text,
	`joining_with_cofounder` text,
	`open_to_join_another_project` text,
	`how_did_you_hear` text,
	`referral_source` text,
	`anything_to_let_us_know` text,
	`introduction` text,
	`tech_skills` text,
	`industries` text,
	`roles_i_could_take` text,
	`track_record_proud` text,
	`anything_else_worth_mentioning` text,
	`interested_in_working_on` text,
	`nationality` text,
	`gender` text,
	`years_of_xp` integer,
	`education` text,
	`degree` text,
	`academic_field` text,
	`companies_worked` text,
	`t_shirt_size` text,
	`t_shirt_handed_out` text,
	`founder` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `session_events` (
	`id` text PRIMARY KEY,
	`name` text,
	`date` integer,
	`program_week` text,
	`type_of_session` text,
	`speaker` text,
	`emails` text,
	`slack_instruction_email_commu` text,
	`participants` text,
	`notes_feedback` text,
	`notes_2` text,
	`attachments` text,
	`name_from_linked` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `startups` (
	`id` text PRIMARY KEY,
	`startup` text,
	`pitch_sequence` integer,
	`industry` text,
	`startup_in_a_word` text,
	`active_inactive` text,
	`weekly_forms` text,
	`main_su_2025` text,
	`main_su_2025_2` text,
	`team_members` text,
	`committee` text,
	`funding_applications` text,
	`startup_evaluation` text,
	`startup_evaluation_copy` text,
	`notes` text,
	`full_notes` text,
	`maxime_comment` text,
	`traction_summary` text,
	`traction_summary_old` text,
	`detailed_progress` text,
	`detailed_progress_old` text,
	`previous_decks` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
